In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/iris/database.sqlite
/kaggle/input/iris/Iris.csv


In [2]:
df = pd.read_csv('../input/iris/Iris.csv', index_col='Id')
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id                                                                           
1              5.1           3.5            1.4           0.2     Iris-setosa
2              4.9           3.0            1.4           0.2     Iris-setosa
3              4.7           3.2            1.3           0.2     Iris-setosa
4              4.6           3.1            1.5           0.2     Iris-setosa
5              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['Species'] = label_encoder.fit_transform(df['Species'])
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
Id                                                                    
1              5.1           3.5            1.4           0.2        0
2              4.9           3.0            1.4           0.2        0
3              4.7           3.2            1.3           0.2        0
4              4.6           3.1            1.5           0.2        0
5              5.0           3.6            1.4           0.2        0
..             ...           ...            ...           ...      ...
146            6.7           3.0            5.2           2.3        2
147            6.3           2.5            5.0           1.9        2
148            6.5           3.0            5.2           2.0        2
149            6.2           3.4            5.4           2.3        2
150            5.9           3.0            5.1           1.8        2

[150 rows x 5 columns]

# import Keras

In [4]:
import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers

In [5]:
tf.__version__

'2.2.0'

# split data into train and val

In [6]:
df_val = df.sample(frac=0.2, random_state=33)
df_val

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
Id                                                                    
97             5.7           2.9            4.2           1.3        1
66             6.7           3.1            4.4           1.4        1
30             4.7           3.2            1.6           0.2        0
55             6.5           2.8            4.6           1.5        1
135            6.1           2.6            5.6           1.4        2
101            6.3           3.3            6.0           2.5        2
25             4.8           3.4            1.9           0.2        0
18             5.1           3.5            1.4           0.3        0
138            6.4           3.1            5.5           1.8        2
121            6.9           3.2            5.7           2.3        2
144            6.8           3.2            5.9           2.3        2
39             4.4           3.0            1.3           0.2        0
137            6.3           3.4            5.6           2.4        2
64             6.1           2.9            4.7           1.4        1
142            6.9           3.1            5.1           2.3        2
75             6.4           2.9            4.3           1.3        1
139            6.0           3.0            4.8           1.8        2
28             5.2           3.5            1.5           0.2        0
57             6.3           3.3            4.7           1.6        1
126            7.2           3.2            6.0           1.8        2
10             4.9           3.1            1.5           0.1        0
19             5.7           3.8            1.7           0.3        0
105            6.5           3.0            5.8           2.2        2
13             4.8           3.0            1.4           0.1        0
120            6.0           2.2            5.0           1.5        2
127            6.2           2.8            4.8           1.8        2
92             6.1           3.0            4.6           1.4        1
72             6.1           2.8            4.0           1.3        1
148            6.5           3.0            5.2           2.0        2
150            5.9           3.0            5.1           1.8        2

In [7]:
df_val.shape

(30, 5)

In [8]:
df_train = df.drop(df_val.index)
df_train

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
Id                                                                    
1              5.1           3.5            1.4           0.2        0
2              4.9           3.0            1.4           0.2        0
3              4.7           3.2            1.3           0.2        0
4              4.6           3.1            1.5           0.2        0
5              5.0           3.6            1.4           0.2        0
..             ...           ...            ...           ...      ...
143            5.8           2.7            5.1           1.9        2
145            6.7           3.3            5.7           2.5        2
146            6.7           3.0            5.2           2.3        2
147            6.3           2.5            5.0           1.9        2
149            6.2           3.4            5.4           2.3        2

[120 rows x 5 columns]

# convert dataframe to tensor data 

In [9]:
# A utility method to create a tf.data dataset from a Pandas Dataframe
def df_to_dataset(dataframe, target, shuffle=True, batch_size=10):
  dataframe = dataframe.copy()
  labels = dataframe.pop(target)
  ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
  if shuffle:
    ds = ds.shuffle(buffer_size=len(dataframe))
  ds = ds.batch(batch_size)
  return ds

In [10]:
train_ds = df_to_dataset(dataframe=df_train, target='Species')
val_ds = df_to_dataset(dataframe=df_val, target='Species')

In [11]:
for b in train_ds.take(1):
    print(b)

({'SepalLengthCm': <tf.Tensor: shape=(10,), dtype=float64, numpy=array([6.5, 7.7, 4.8, 5.7, 6.9, 5.2, 5. , 5.8, 7.7, 6.4])>, 'SepalWidthCm': <tf.Tensor: shape=(10,), dtype=float64, numpy=array([3.2, 3. , 3.4, 2.8, 3.1, 2.7, 3.3, 2.7, 2.6, 2.8])>, 'PetalLengthCm': <tf.Tensor: shape=(10,), dtype=float64, numpy=array([5.1, 6.1, 1.6, 4.5, 5.4, 3.9, 1.4, 3.9, 6.9, 5.6])>, 'PetalWidthCm': <tf.Tensor: shape=(10,), dtype=float64, numpy=array([2. , 2.3, 0.2, 1.3, 2.1, 1.4, 0.2, 1.2, 2.3, 2.1])>}, <tf.Tensor: shape=(10,), dtype=int64, numpy=array([2, 2, 0, 1, 2, 1, 0, 1, 2, 2])>)


# prepare input layer 

In [12]:
from tensorflow import feature_column

feature_columns = []
# numeric cols
for col in df.columns:
  if col == 'Species':
    continue
  feature_columns.append(feature_column.numeric_column(col, dtype=tf.float16)) 
feature_columns

[NumericColumn(key='SepalLengthCm', shape=(1,), default_value=None, dtype=tf.float16, normalizer_fn=None),
 NumericColumn(key='SepalWidthCm', shape=(1,), default_value=None, dtype=tf.float16, normalizer_fn=None),
 NumericColumn(key='PetalLengthCm', shape=(1,), default_value=None, dtype=tf.float16, normalizer_fn=None),
 NumericColumn(key='PetalWidthCm', shape=(1,), default_value=None, dtype=tf.float16, normalizer_fn=None)]

# define model 

In [13]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.DenseFeatures(feature_columns))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(3, activation='softmax'))

# compile model

1. optimizer
2. loss
3. metircs 

In [14]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', 
             metrics=['accuracy'])

# evalute before training (evalute on random wieghts) 

In [15]:
model.evaluate(val_ds)

3/3 [==============================] - 0s 2ms/step - loss: 2.4272 - accuracy: 0.4667


[2.427220582962036, 0.46666666865348816]

# train the model using fit fucntion 

In [16]:
model.fit(train_ds, epochs=10, validation_data=val_ds)

Epoch 1/10
12/12 [==============================] - 0s 3ms/step - loss: 2.6798 - accuracy: 0.3000 - val_loss: 1.7623 - val_accuracy: 0.4667
Epoch 2/10
12/12 [==============================] - 0s 3ms/step - loss: 1.9025 - accuracy: 0.3000 - val_loss: 1.2815 - val_accuracy: 0.4667
Epoch 3/10
12/12 [==============================] - 0s 3ms/step - loss: 1.3736 - accuracy: 0.3000 - val_loss: 1.0368 - val_accuracy: 0.4667
Epoch 4/10
12/12 [==============================] - 0s 3ms/step - loss: 1.0925 - accuracy: 0.3000 - val_loss: 0.9567 - val_accuracy: 0.4667
Epoch 5/10
12/12 [==============================] - 0s 3ms/step - loss: 0.9765 - accuracy: 0.5083 - val_loss: 0.9290 - val_accuracy: 0.7000
Epoch 6/10
12/12 [==============================] - 0s 3ms/step - loss: 0.9182 - accuracy: 0.7500 - val_loss: 0.8846 - val_accuracy: 0.8000
Epoch 7/10
12/12 [==============================] - 0s 3ms/step - loss: 0.8695 - accuracy: 0.7833 - val_loss: 0.8362 - val_accuracy: 0.7667
Epoch 8/10
12/12 [==

# model summary 

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_features (DenseFeature multiple                  0         
_________________________________________________________________
dense (Dense)                multiple                  160       
_________________________________________________________________
dense_1 (Dense)              multiple                  99        
Total params: 259
Trainable params: 259
Non-trainable params: 0
_________________________________________________________________


# evaluate (after training)

In [18]:
model.evaluate(val_ds)

3/3 [==============================] - 0s 1ms/step - loss: 0.7203 - accuracy: 0.8667


[0.7202627658843994, 0.8666666746139526]

# get predictions 

In [19]:
model.predict(val_ds)

array([[0.10252071, 0.27022487, 0.62725437],
       [0.1312612 , 0.38367978, 0.48505908],
       [0.550621  , 0.21756586, 0.23181313],
       [0.11041504, 0.36656758, 0.52301735],
       [0.51674205, 0.21242867, 0.2708293 ],
       [0.19417463, 0.35257685, 0.45324853],
       [0.12686059, 0.33739364, 0.53574574],
       [0.10565899, 0.3371954 , 0.55714566],
       [0.10564242, 0.33395398, 0.56040365],
       [0.19274649, 0.43736818, 0.36988527],
       [0.1207377 , 0.43046856, 0.4487937 ],
       [0.1902354 , 0.37035432, 0.43941024],
       [0.19276297, 0.4401282 , 0.36710882],
       [0.21306665, 0.36617172, 0.42076164],
       [0.20243658, 0.43968832, 0.35787502],
       [0.51723415, 0.22710094, 0.2556649 ],
       [0.13710664, 0.3294132 , 0.5334801 ],
       [0.5161697 , 0.23600248, 0.24782781],
       [0.16108419, 0.4463981 , 0.39251772],
       [0.51369697, 0.2428543 , 0.24344866],
       [0.1240894 , 0.29056168, 0.5853489 ],
       [0.1784927 , 0.3755378 , 0.4459694 ],
       [0.

# get predickions as 0, 1, 2

In [20]:
np.argmax([0.2, 0.9, 0.01])

1

In [21]:
np.argmax([0.8, 0.19, 0.01])

0

In [22]:
np.argmax([0.08, 0.19, 0.71])

2

In [23]:
predictions = np.argmax(model.predict(val_ds), axis=1)
predictions

array([0, 2, 2, 0, 2, 0, 2, 2, 2, 0, 0, 0, 1, 1, 0, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 2, 0, 1, 2, 2, 2])

In [24]:
len(predictions)

30

# predict a new example 

In [25]:
df.keys()

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [26]:
df.columns

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [27]:
new_data = {
    'SepalLengthCm': [5.0],
    'SepalWidthCm': [1.2], 
    'PetalLengthCm': [3.5],
    'PetalWidthCm': [0.7]
}
new_data

{'SepalLengthCm': [5.0],
 'SepalWidthCm': [1.2],
 'PetalLengthCm': [3.5],
 'PetalWidthCm': [0.7]}

In [28]:
input_dict = {name: tf.convert_to_tensor([value]) for name, value in new_data.items()}
input_dict

{'SepalLengthCm': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[5.]], dtype=float32)>,
 'SepalWidthCm': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[1.2]], dtype=float32)>,
 'PetalLengthCm': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[3.5]], dtype=float32)>,
 'PetalWidthCm': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.7]], dtype=float32)>}

In [29]:
model.predict(input_dict)

array([[0.15400903, 0.5226812 , 0.3233098 ]], dtype=float32)

In [30]:
np.argmax(model.predict(input_dict))

1